recently_files:
- E:/Documents/GitHub/ThreeCrows/台本テスト.tcs
- E:/Documents/GitHub/ThreeCrows/aaa.tcs
- E:/Documents/GitHub/ThreeCrows/は.tcs
- E:/Documents/GitHub/ThreeCrows/noname copy.tcs
- E:/Documents/GitHub/ThreeCrows/noname copy - コピー.tcs
statusbar_element_settings:
  0:
  - hotkeys3
  1:
  - hotkeys2
  2:
  - hotkeys1
  3:
  - st2_letter_count
  - st2_line_count
  - st3_letter_count
  - st3_line_count
  4:
  - 
  5:
  -
